spring:
  application:
    name: Medicina Interna
  datasource:
    url: jdbc:postgresql://localhost:5432/Medicina%20Interna
    username: ${DB_USER} #Variables del sistema con este nombre. Reemplazar en cada caso
    password: ${DB_PASSWORD} #Variables del sistema con este nombre. Reemplazar en cada caso
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 60000
  jpa:
    format-sql : true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
      javax:
        persistence:
          query:
            timeout : 60000
    database: postgresql
    show-sql: true
  banner:
    location: templates/banner.txt
  flyway:
    baseline-on-migrate: true
    enabled: true
    locations: classpath:db/migration
server:
  port: 8085
  error:
    include-stacktrace: never
